version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # Синхронизируем папку с базой данных на ПК с папкой в контейнере
      # Замените ./instance на путь, где у вас лежит файл .db, если он в другой папке
      # Обычно Flask создает папку 'instance' для SQLite
      - ./instance:/app/instance

      # Альтернатива: если ваш db файл лежит прямо в корне проекта, раскомментируйте строку ниже:
      # - ./database.db:/app/database.db